name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  container_scanning:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: build local container
          uses: docker/build-push-action@v2
          with:
            tags: mhaidir32/node-js-sample-akash:${{ github.sha }}
            push: false
            load: true
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'mhaidir32/node-js-sample-akash:${{ github.sha }}'
            format: 'json'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'MEDIUM'
          continue-on-error: true             # allow the build to fail, similar to "allow_failure: true" in GitLab